---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dongyf.
--- DateTime: 2019-06-08 10:54
---

local utils = {}

function utils.makeClass( t, super )

    if super then
        local mt = {
            __call=function(t,...)
                return t.new(...)
            end,
            __index = function(table, key)
                if not super then
                    return nil
                else
                    return super[key]
                end
            end,
        }
        t.__super = super
        setmetatable(t, mt)

        t.new = function( ... )
            local o = {}
            setmetatable( o, { __index = t } )
            if o.init then
                o.init(o, ...)
            end
            return o
        end

    else
        local mt = {
            __call = function(t,...)
                return t.new(...)
            end
        }
        setmetatable(t, mt)
        t.__index = t

        t.new = function(...)
            local ret = {}
            setmetatable(ret, t)
            if t.init then
                t.init(ret, ...)
            end

            return ret
        end
    end
end

return utils