---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dongyf.
--- DateTime: 2019-06-07 16:01
---
local skynet = require("skynet")
local data = require('data.roomData')
local libroompool = require("libroompool")

local faci = require "faci.module"
local env = require'faci.env'
local module = faci.get_module("roomManager")
local dispatch = module.dispatch

local roomManagerLogic = {}

function roomManagerLogic.init()
    --创建mode为2的房间
    local roomData = data.roomData
    for id, roomInfo in pairs(roomData) do
        if roomInfo.roomMode == 2 and env.id == 1 then
            dispatch.create(id, roomInfo.gameType, roomInfo.roomMode)
        end
    end
end

function roomManagerLogic.get_one_room (roomService, roomName, roomId)
    return libroompool.get()
    --return skynet.newservice(roomService, "room", roomId)
end

function roomManagerLogic.recycle(room)
    return libroompool.recycle(room)
end

return roomManagerLogic