---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dongyf.
--- DateTime: 2019-06-03 00:33
---
---

require("base.init")

local name, id = ...
local s = require "faci.service"
s.init(name, id)